name: "Bicep Linting"
description: "Composite action for running Bicep Linting"
branding:
  icon: 'code'
  color: 'blue'
inputs:
  allfiles:
    type: boolean
    description: 'Check all files or only the changed files'
    default: false
  create-sarif:
    description: 'Create a combined SARIF file'
    type: boolean
    default: true
  markdown-report:
    description: 'Create a markdown report'
    type: boolean
    default: false
  sarif-output-path:
    description: 'The file path to save the SARIF file'
    type: string
    default: 'bicep-lint.sarif'
  markdown-output-path:
    description: 'The file path to save the markdown report'
    type: string
    default: 'bicep-lint.md'
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get files
        shell: pwsh
        run: |
          $allFiles = [System.Convert]::ToBoolean("${{ inputs.allfiles }}")
          ${{ github.action_path }}\Get-BicepFiles.ps1 -AllFiles $allFiles
      - name: "Linting the bicep files"
        run: |
          $sarif = [System.Convert]::ToBoolean("${{ inputs.create-sarif }}")
          $markdown = [System.Convert]::ToBoolean("${{ inputs.markdown-report }}")
          ${{ github.action_path }}\Get-BicepLintingResults.ps1 -BicepFilesJson ${{ env.BICEP_FILES }} `
                     -CreateSarif $sarif `
                     -MarkdownReport $markdown `
                     -SarifOutputPath ${{ inputs.sarif-output-path }} `
                     -MarkdownOutputPath ${{ inputs.markdown-output-path }}
        shell: pwsh

